python vis_mask2image.py \
--dataroot=datasets/ade20k/ \
--dataloader ade20k \
--name pretrained_mask2image_ade \
--model pix2pixHD_condImg \
--no_instance \
--resize_or_crop select_region \
--loadSize 512 \
--fineSize 256 \
--contextMargin 3.0 \
--prob_bg 0.1 \
--label_nc 49 \
--output_nc 3 \
--load_image \
--batchSize 1 \
--nThreads 1 \
--norm instance \
--n_downsample_global 4 \
--netG global_twostream \
--min_box_size 64 \
--which_encoder ctx_label \
--use_skip \
--use_output_gate \
--how_many 200 \
--phase val \
--gpu_ids 0 \

